# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
