# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='BirthDate',
            field=models.DateField(default=datetime.datetime(2016, 5, 27, 11, 2, 50, 748000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='LastName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='MiddleName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Citizenship',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='management.Citizenship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='CivilStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.CivilStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='StudentType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.StudentType'),
            preserve_default=False,
        ),
    ]
