# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:56
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160527_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StdNum',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 11, 56, 36, 45000, tzinfo=utc), max_length=9, validators=[django.core.validators.RegexValidator('\\d{1,10})', 'Invalid input!')]),
            preserve_default=False,
        ),
    ]
