# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_student_stdnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='LastName',
        ),
        migrations.AddField(
            model_name='student',
            name='SUser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='StdNum',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('\\d{1,10}', 'Invalid input!')]),
        ),
    ]
