# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20160528_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=3)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('DaysOffered', models.CharField(max_length=100)),
                ('Room', models.CharField(max_length=50)),
                ('ClassCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNum', models.FloatField()),
                ('Desc', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=60)),
                ('Units', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComponentID', models.IntegerField()),
                ('isRequired', models.BooleanField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField()),
                ('Year', models.CharField(max_length=10)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreReqID', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=100)),
                ('isGovernment', models.BooleanField()),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BracketName', models.CharField(max_length=10)),
                ('BracketDesc', models.CharField(max_length=100)),
                ('PercentDiscount', models.FloatField()),
                ('Stipend', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STSID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.STS')),
                ('ScholarshipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=6)),
                ('Desc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='StdNum',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Invalid input!')]),
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.SubjectStatus'),
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
        migrations.AddField(
            model_name='studentfinance',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ScheduleStatus'),
        ),
        migrations.AddField(
            model_name='class',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Teacher'),
        ),
    ]
