# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipstatus',
            name='Desc',
            field=models.CharField(max_length=50),
        ),
    ]
