# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20160529_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='Degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Degree'),
        ),
    ]
