# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_student_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseNumber', models.CharField(max_length=10)),
                ('Brgy', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Landline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='AddressType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.AddressType'),
        ),
        migrations.AddField(
            model_name='address',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
    ]
