# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20160530_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='AddressType',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Brgy',
        ),
        migrations.RemoveField(
            model_name='address',
            name='City',
        ),
        migrations.RemoveField(
            model_name='address',
            name='HouseNumber',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Landline',
        ),
        migrations.RemoveField(
            model_name='address',
            name='StudentID',
        ),
        migrations.AddField(
            model_name='address',
            name='Desc',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
