# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20160530_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('HouseNumber', models.CharField(max_length=100)),
                ('Barangay', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Landline', models.CharField(max_length=100)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100)),
                ('FatherOccu', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('MotherOccu', models.CharField(max_length=100)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SendDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('HouseNumber', models.CharField(max_length=100)),
                ('Barangay', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Landline', models.CharField(max_length=100)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
    ]
